apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: test-workflow:bcbcce948d387f69114feb28c7e99f2f1d49931f
        name: nginx
        ports:
        - containerPort: 80
