apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: test-workflow:a54c0440db18d8e2dbc881b0169ed0aad3720ffd
        name: nginx
        ports:
        - containerPort: 80
