apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: test-workflow:b760096866e8f24252934c7f88d10a87db4cf522
        name: nginx
        ports:
        - containerPort: 80
