# NOTE: https://docs.github.com/ja/actions/using-workflows/reusing-workflows
name: Dispatch repository workflow

on:
  workflow_call:
    inputs:
      repository:
        description: "The full name of the repository to send the dispatch"
        type: string
        required: true
      event-type:
        description: "A custom webhook event name"
        type: string
        required: true
      client-payload:
        description: "JSON payload with extra information about the webhook event that your action or workflow may use"
        type: string
        default: "{}"
    secrets:
      app-id:
        description: "GitHub App ID"
        required: true
      private-key:
        description: "GitHub App private key"
        required: true

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      # get GitHub App token
      #----------------------------------------------
      # NOTE: https://github.com/marketplace/actions/action-github-app-token
      - name: Get GitHub App token
        id: get-github-app-token
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.app-id }}
          private_key: ${{ secrets.private-key }}

      #----------------------------------------------
      # check-out repo
      #----------------------------------------------
      - name: Check out repository
        id: check-out-repository
        uses: actions/checkout@v3

      #----------------------------------------------
      # dispatch
      #----------------------------------------------
      # NOTE: https://github.com/marketplace/actions/repository-dispatch
      - name: Repository Dispatch
        id: repository-dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ steps.get-github-app-token.outputs.token }}
          repository: ${{ inputs.repository }}
          event-type: ${{ inputs.event-type }}
          client-payload: ${{ inputs.client-payload }}
