# NOTE: https://docs.github.com/ja/actions/using-workflows/reusing-workflows
name: Docker check workflow

on:
  workflow_call:
    inputs:
      working-directory:
        description: "workdir"
        type: string
        default: "."
      docker-tag:
        description: "docker tag"
        type: string
        default: "docker-image:github-actions"
      dockerfile-name:
        description: "dockerfile name"
        type: string
        default: "Dockerfile"

jobs:
  check-docker:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      # check-out repo & set-up python
      #----------------------------------------------
      - name: Check out repository
        id: check-out-repository
        uses: actions/checkout@v3

      #----------------------------------------------
      # lint dockerfile
      #----------------------------------------------
      # NOTE: https://github.com/marketplace/actions/hadolint-action
      - name: Lint dockerfile
        id: lint-dockerfile
        uses: hadolint/hadolint-action@v2.0.0
        env:
          DOCKER_CONTENT_TRUST: 0
        with:
          dockerfile: ${{ inputs.working-directory }}/${{ inputs.dockerfile-name }}

      #----------------------------------------------
      # build docker
      #----------------------------------------------
      - name: Build docker
        id: build-docker
        working-directory: ${{ inputs.working-directory }}
        run: docker build --no-cache -t ${{ inputs.docker-tag }} -f ${{ inputs.dockerfile-name }} .

      #----------------------------------------------
      # scan with dockle
      #----------------------------------------------
      - name: Run dockle
        id: run-dockle
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            goodwithtech/dockle:latest --no-color ${{ inputs.docker-tag }}

      #----------------------------------------------
      # scan with trivy
      #----------------------------------------------
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.5.1
        with:
          image-ref: ${{ inputs.docker-tag }}
          format: "table"
          ignore-unfixed: true
          output: "trivy-results.txt"
