# NOTE: https://docs.github.com/ja/actions/using-workflows/reusing-workflows
name: Kustomize edit pull request workflow

on:
  workflow_call:
    secrets:
      app-id:
        description: "GitHub App ID"
        required: true
      private-key:
        description: "GitHub App private key"
        required: true
      docker-tag:
        description: "docker tag"
        required: true
    inputs:
      image-set-directory:
        description: "image set directory"
        type: string
        default: ""
      build-input-directory:
        description: "image set directory"
        type: string
        default: "."
      target-image-name:
        description: "target image name"
        type: string
        default: ""
      build-output-file-path:
        description: "build output file name"
        type: string
        default: "./build/build.yaml"

jobs:
  kustomize-edit-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
      pull-requests: "write"
    steps:
      #----------------------------------------------
      # get GitHub App token
      #----------------------------------------------
      # NOTE: https://github.com/marketplace/actions/action-github-app-token
      - name: Get GitHub App token
        id: get-github-app-token
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.app-id }}
          private_key: ${{ secrets.private-key }}

      #----------------------------------------------
      # check-out repo & set-up python
      #----------------------------------------------
      - name: Check out repository
        id: check-out-repository
        uses: actions/checkout@v3

      #----------------------------------------------
      # install kustomize
      #----------------------------------------------
      - name: Install kustomize
        id: install-kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          echo "$HOME/kustomize" >> $GITHUB_PATH

      #----------------------------------------------
      # update image with kustomize
      #----------------------------------------------
      - name: Update image with kustomize
        id: update-image-with-kustomize
        if: ${{ inputs.target-image-name != "" && inputs.image-set-directory != "" }}
        working-directory: ${{ inputs.image-set-directory }}
        run: kustomize edit set image ${{ inputs.target-image-name }}=${{ secrets.docker-tag }}

      #----------------------------------------------
      # build yaml with kustomize
      #----------------------------------------------
      - name: Build yaml with kustomize
        id: build-yaml-with-kustomize
        run: kustomize build ${{ inputs.build-input-directory }} > ${{ inputs.build-output-file-path }}

      #----------------------------------------------
      # create pull request
      #----------------------------------------------
      - name: Create Pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.get-github-app-token.outputs.token }}
          commit-message: "chore: update image"
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          branch: "kustomize/patch"
          branch-suffix: "short-commit-hash"
          delete-branch: true
          title: "[kustomize] build ${{ inputs.build-input-directory }}"
          body: |
            Build a set of KRM resources
            - updated image: `${{ inputs.working-directory }}:${{ inputs.target-image-name }}`
            - build input: `${{ inputs.build-input-directory }}`
            - build output: `${{ inputs.build-output-file-path }}`
          labels: |
            kustomize
