# NOTE: https://docs.github.com/ja/actions/using-workflows/reusing-workflows
name: Repository dispatch workflow

on:
  workflow_call:
    secrets:
      token:
        description: "GitHub Token"
      app-id:
        description: "GitHub App ID"
      private-key:
        description: "GitHub App private key"
    inputs:
      repository:
        description: "https://github.com/peter-evans/repository-dispatch/blob/v2.0.0/action.yml#L7-L9"
        type: string
        required: true
      event-type:
        description: "https://github.com/peter-evans/repository-dispatch/blob/v2.0.0/action.yml#L10-L12"
        type: string
        required: true
      client-payload:
        description: "https://github.com/peter-evans/repository-dispatch/blob/v2.0.0/action.yml#L13-L15"
        type: string
        default: "{}"

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      # set env TOKEN
      #----------------------------------------------
      # NOTE: https://github.com/marketplace/actions/action-github-app-token
      - name: Get GitHub App token
        id: get-github-app-token
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.app-id }}
          private_key: ${{ secrets.private-key }}
        continue-on-error: true

      - name: Set env token
        id: set-env-token
        run: |
          echo 'TOKEN=${{ steps.get-github-app-token.outputs.token  || secrets.token }}' >> $GITHUB_ENV

      #----------------------------------------------
      # check-out repo
      #----------------------------------------------
      - name: Check out repository
        id: check-out-repository
        uses: actions/checkout@v3

      #----------------------------------------------
      # dispatch
      #----------------------------------------------
      # NOTE: https://github.com/marketplace/actions/repository-dispatch
      - name: Repository Dispatch
        id: repository-dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ env.TOKEN }}
          repository: ${{ inputs.repository }}
          event-type: ${{ inputs.event-type }}
          client-payload: ${{ inputs.client-payload }}
