# NOTE: https://docs.github.com/ja/actions/using-workflows/reusing-workflows
name: Submodules update workflow

on:
  workflow_call:
    secrets:
      token:
        description: |
          GitHub Token.
          If private repository is included as submodules,
          you might be better using GitHub App.

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      # check-out repo
      #----------------------------------------------
      - name: Check out repository
        id: check-out-repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.token }}

      #----------------------------------------------
      # update submodules
      #----------------------------------------------
      - name: Update submodules
        id: update-submodules
        run: git submodule update --remote --recursive

      - name: Get git status
        id: get-git-status
        run: echo "::set-output name=status::$(git status -s)"

      - name: Commit and push
        id: commit-and-push
        if: ${{ steps.get-git-status.outputs.status }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add -u .
          git commit --author=. -m 'chore: update submodules'
          git push
