# NOTE: https://docs.github.com/ja/actions/using-workflows/reusing-workflows
name: Terraform with google cloud workflow

on:
  workflow_call:
    secrets:
      workload-identity-provider:
        description: "https://github.com/google-github-actions/auth/blob/95a6bc2a27ae409a01ea58dd0732eccaa088ec07/action.yml#L30-L34"
        required: true
      service-account:
        description: "https://github.com/google-github-actions/auth/blob/95a6bc2a27ae409a01ea58dd0732eccaa088ec07/action.yml#L38-L40"
        required: true
      backend-gcs:
        description: "backend gcs bucket name"
        required: true
      tf-vars:
        description: "terraform vars"
        required: true
    inputs:
      environment-directory:
        description: "environment directory path"
        type: string
        default: "."
      terraform-version:
        description: "terraform version"
        type: string
        required: true
      comamnd-check-format:
        description: "format check command"
        type: string
        default: "terraform fmt -recursive -check"
      command-lint:
        description: "lint command"
        type: string
        default: "terraform validate"
      do-plan:
        description: "whether to execute plan command"
        type: boolean
        default: false
      do-apply:
        description: "whether to execute apply command"
        type: boolean
        default: false

jobs:
  terraform:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      #----------------------------------------------
      # check-out repo
      #----------------------------------------------
      - name: Check out repository
        id: check-out-repository
        uses: actions/checkout@v3

      #----------------------------------------------
      # authenticate to google cloud & set env
      #----------------------------------------------
      - name: Authenticate to Google Cloud
        id: authenticate-to-google-cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.workload-identity-provider }}
          service_account: ${{ secrets.service-account }}

      - name: Set environment for terraform
        id: set-environment-for-terraform
        run: |
          echo "GOOGLE_CREDENTIALS=${{ steps.authenticate-to-google-cloud.credentials_file_path }}" >> $GITHUB_ENV
          echo "${{ secrets.tf-vars }}" >> $GITHUB_ENV

      #----------------------------------------------
      # setup terraform
      #----------------------------------------------
      - name: Setup Terraform
        id: setup-terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform-version }}

      #----------------------------------------------
      # run test suite
      #----------------------------------------------
      - name: Check format
        id: check-format
        run: ${{ inputs.command-check-format }}

      - name: lint
        id: lint
        run: ${{ inputs.command-lint}}

      #----------------------------------------------
      # init terraform
      #----------------------------------------------
      - name: Init
        id: init
        working-directory: ${{ inputs.environment-directory }}
        run: "terraform init -backend-config='bucket=${{secrets.backend-gcs}}'"

      #----------------------------------------------
      # plan
      #----------------------------------------------
      - name: Plan
        id: plan
        if: ${{ inputs.do-plan }}
        working-directory: ${{ inputs.environment-directory }}
        run: "terraform plan"
        continue-on-error: true

      #----------------------------------------------
      # apply
      #----------------------------------------------
      - name: Apply
        id: apply
        # if: ${{ inputs.do-apply && steps.plan.outcome == 'success' }}
        if: ${{ inputs.do-plan && steps.plan.outcome == 'success' }}
        working-directory: ${{ inputs.environment-directory }}
        # run: "terraform apply -auto-approve"
        run: "echo DEBUG NOW"
