name: Test python code check workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/python-code-check.yaml"
      - ".github/workflows/test-python-code-check.yaml"
      - "test_stubs/python/**"
      - "!**.md"

jobs:
  test-normal:
    uses: koei-kaji/msa-hands-on-backends/.github/workflows/python-code-check.yaml
    with:
      python-version: "3.10.5"
      pip-version: "22.1.2"
      poetry-version: "1.1.13"
      working-directory: "./test_stubs/python/"
      command-check-format: "make format-check"
      command-lint: "make lint"
      command-test: "make test"
