# NOTE: https://docs.github.com/ja/actions/using-workflows/reusing-workflows
name: Update submodules workflow

on:
  workflow_call:
    secrets:
      app-id:
        description: "GitHub App ID"
        required: true
      private-key:
        description: "GitHub App private key"
        required: true

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      # get GitHub App token
      #----------------------------------------------
      # NOTE: https://github.com/marketplace/actions/action-github-app-token
      - name: Get GitHub App token
        id: get-github-app-token
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.app-id }}
          private_key: ${{ secrets.private-key }}

      #----------------------------------------------
      # check-out repo
      #----------------------------------------------
      - name: Check out repository
        id: check-out-repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ steps.get-github-app-token.outputs.token }}

      #----------------------------------------------
      # update submodules
      #----------------------------------------------
      - name: Update submodules
        id: update-submodules
        run: git submodule update --remote --recursive

      - name: Get git status
        id: get-git-status
        run: echo "::set-output name=status::$(git status -s)"

      - name: Commit and push
        id: commit-and-push
        if: ${{ steps.get-git-status.outputs.status }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add -u .
          git commit --author=. -m 'chore: update submodules'
          git push
